--3.1(A)
SELECT UPPER(SUBSTR(COUNTRY_NAME, 1, 3)) FIRST_THREE_CHAR, 
       UPPER(SUBSTR(COUNTRY_NAME, LENGTH (COUNTRY_NAME)-2, 3)) LAST
FROM COUNTRIES;

--3.1(B)
SELECT LPAD(CONCAT(CONCAT(FIRST_NAME, ' '),LAST_NAME), 60, '*') NAME
FROM EMPLOYEES
WHERE (LENGTH(FIRST_NAME) + LENGTH(LAST_NAME) + 1) <= 60;

SELECT LPAD(FIRST_NAME || ' ' || LAST_NAME, 60, '*') AS NAME
FROM EMPLOYEES
WHERE (LENGTH(FIRST_NAME) + LENGTH(LAST_NAME) + 1) <= 60;

--3.1(C)
SELECT JOB_TITLE 
FROM JOBS
WHERE LOWER(JOB_TITLE) LIKE '%manager%';
