--2.2(A)
SELECT (FIRST_NAME||' '||LAST_NAME) NAME
FROM EMPLOYEES
WHERE HIRE_DATE < '01-JAN-1998';

--2.2(B)
SELECT *
FROM LOCATIONS
WHERE COUNTRY_ID IN ('CA','DE','UK');

--2.2(C)
SELECT FIRST_NAME 
FROM EMPLOYEES
WHERE COMMISSION_PCT  IS NULL;

--2.2(D)
SELECT FIRST_NAME 
FROM EMPLOYEES
WHERE LAST_NAME  LIKE 'A%';

--2.2(E)
SELECT FIRST_NAME 
FROM EMPLOYEES 
WHERE LAST_NAME LIKE 'S%n';


--2.2(F)
SELECT DEPARTMENT_NAME 
FROM DEPARTMENTS
WHERE MANAGER_ID = 100;


--2.2(G)
SELECT (FIRST_NAME||' '||LAST_NAME) NAME
FROM EMPLOYEES
WHERE JOB_ID='AD_PRES' AND SALARY >=23000;

--2.2(H)
SELECT (FIRST_NAME||' '||LAST_NAME) NAME
FROM EMPLOYEES
WHERE NOT(LOWER(LAST_NAME)LIKE '%s%');

--2.2(I)
SELECT (FIRST_NAME||' '||LAST_NAME) NAME, COMMISSION_PCT 
FROM EMPLOYEES
WHERE COMMISSION_PCT <=0.3 OR COMMISSION_PCT IS NULL;


--2.2(J)
SELECT (FIRST_NAME||' '||LAST_NAME) NAME
FROM EMPLOYEES
WHERE HIRE_DATE > '01-JAN-1998';

--2.2(K)
SELECT (FIRST_NAME||' '||LAST_NAME) NAME
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN  '01-JAN-1998' AND '31-DEC-1998';



