--4.3(A)
SELECT
    CASE
        WHEN SALARY BETWEEN 0 AND 4999 THEN 'Group 1: 0 to <5K'
        WHEN SALARY BETWEEN 5000 AND 9999 THEN 'Group 2: 5K to <10K'
        WHEN SALARY BETWEEN 10000 AND 14999 THEN 'Group 3: 10K to <15K'
        ELSE 'Other'
    END AS SALARY_GROUP,
    COUNT(*) AS EMPLOYEE_COUNT
FROM
    EMPLOYEES
GROUP BY
    CASE
        WHEN SALARY BETWEEN 0 AND 4999 THEN 'Group 1: 0 to <5K'
        WHEN SALARY BETWEEN 5000 AND 9999 THEN 'Group 2: 5K to <10K'
        WHEN SALARY BETWEEN 10000 AND 14999 THEN 'Group 3: 10K to <15K'
        ELSE 'Other'
    END;
   
   
   --4.3(B)
SELECT
    EXTRACT(YEAR FROM HIRE_DATE) AS HIRE_YEAR,
    JOB_ID,
    COUNT(*) AS TOTAL_EMPLOYEES_HIRED
FROM
    EMPLOYEES
GROUP BY
    EXTRACT(YEAR FROM HIRE_DATE),
    JOB_ID
ORDER BY
    HIRE_YEAR,
    JOB_ID;
    
